const EngineToWidgetToolAction = {
  // Navigation
  GET_PAGE_CONTEXT: "GET_PAGE_CONTEXT",
  GET_ALL_LINKS: "GET_ALL_LINKS",
  NAVIGATE_TO_URL: "NAVIGATE_TO_URL",
  // Interaction
  GET_INTERACTIVE_ELEMENTS: "GET_INTERACTIVE_ELEMENTS",
  HIGHLIGHT_ELEMENT: "HIGHLIGHT_ELEMENT",
  CLICK_ELEMENT: "CLICK_ELEMENT",
  FILL_INPUT_FIELD: "FILL_INPUT_FIELD",
  SELECT_DROPDOWN_OPTION: "SELECT_DROPDOWN_OPTION",
  SCROLL_PAGE: "SCROLL_PAGE",
  // Visual
  TAKE_SCREENSHOT: "TAKE_SCREENSHOT",
  START_SCREEN_RECORDING: "START_SCREEN_RECORDING",
  START_ELEMENT_SELECTOR: "START_ELEMENT_SELECTOR",
  STOP_RECORDING: "STOP_RECORDING",
  // UI
  UPDATE_UI_STATE: "UPDATE_UI_STATE",
  REQUEST_USER_INPUT: "REQUEST_USER_INPUT",
  DISPLAY_IVR_OPTIONS: "DISPLAY_IVR_OPTIONS",
  ADD_TRANSCRIPT_MESSAGE: "ADD_TRANSCRIPT_MESSAGE",
  // Knowledge
  KNOWLEDGE_BASE_SEARCH: "KNOWLEDGE_BASE_SEARCH",
  CHECK_AUTHENTICATION: "CHECK_AUTHENTICATION",
  // Escalation
  ESCALATE_TO_HUMAN: "ESCALATE_TO_HUMAN",
  REPORT_ERROR: "REPORT_ERROR",
  CHECK_OWNER_AVAILABILITY: "CHECK_OWNER_AVAILABILITY",
  DRAFT_EMAIL: "DRAFT_EMAIL",
  // Tab
  BRING_TAB_TO_FRONT: "BRING_TAB_TO_FRONT",
  FIND_TEXT_PATTERN: "FIND_TEXT_PATTERN",
  GET_PAGE_METADATA: "GET_PAGE_METADATA",
  EXTRACT_STRUCTURED_DATA: "EXTRACT_STRUCTURED_DATA",
  CLEAR_HIGHLIGHTS: "CLEAR_HIGHLIGHTS"
};
const AgentToolName = {
  // Navigation
  GET_PAGE_CONTEXT: "get_page_context",
  GET_ALL_LINKS: "get_all_links",
  NAVIGATE_TO_URL: "navigate_to_url",
  // Interaction
  GET_INTERACTIVE_ELEMENTS: "get_interactive_elements",
  HIGHLIGHT_ELEMENT: "highlight_element",
  CLICK_ELEMENT: "click_element",
  FILL_INPUT_FIELD: "fill_input_field",
  SELECT_DROPDOWN_OPTION: "select_dropdown_option",
  SCROLL_PAGE: "scroll_page",
  // Visual
  TAKE_SCREENSHOT: "take_screenshot",
  START_SCREEN_RECORDING: "start_screen_recording",
  START_ELEMENT_SELECTOR: "start_element_selector",
  // UI
  REQUEST_USER_INPUT: "request_user_input",
  DISPLAY_IVR_OPTIONS: "display_ivr_options",
  // Knowledge
  KNOWLEDGE_BASE_SEARCH: "knowledge_base_search",
  CHECK_AUTHENTICATION: "check_authentication",
  // Escalation
  ESCALATE_TO_HUMAN: "escalate_to_human",
  REPORT_ERROR: "report_error",
  CHECK_OWNER_AVAILABILITY: "check_owner_availability",
  DRAFT_EMAIL: "draft_email",
  // Tab
  BRING_TAB_TO_FRONT: "bring_tab_to_front",
  FIND_TEXT_PATTERN: "find_text_pattern",
  GET_PAGE_METADATA: "get_page_metadata",
  EXTRACT_STRUCTURED_DATA: "extract_structured_data"
};
const EngineToWidgetAction = {
  EXECUTE_TOOL: "EXECUTE_TOOL",
  SHOW_WIDGET: "SHOW_WIDGET",
  HIDE_WIDGET: "HIDE_WIDGET",
  TOGGLE_WIDGET: "TOGGLE_WIDGET"
};
const WidgetToEngineAction = {
  START_CALL: "START_CALL",
  CALL_STARTED: "CALL_STARTED",
  END_CALL: "END_CALL",
  CALL_ENDED: "CALL_ENDED",
  UPDATE_VOLUME: "UPDATE_VOLUME",
  TOGGLE_MIC_MUTE: "TOGGLE_MIC_MUTE",
  SEND_CONTEXT_UPDATE: "SEND_CONTEXT_UPDATE",
  SEND_USER_MESSAGE: "SEND_USER_MESSAGE",
  GET_PAGE_CONTEXT: "GET_PAGE_CONTEXT",
  CONVERSATION_CONNECTED: "CONVERSATION_CONNECTED",
  CONVERSATION_DISCONNECTED: "CONVERSATION_DISCONNECTED",
  CONVERSATION_ERROR: "CONVERSATION_ERROR",
  CAPTURE_SCREENSHOT: "CAPTURE_SHOT",
  START_SCREEN_RECORDING: "START_SCREEN_RECORDING",
  STOP_RECORDING: "STOP_RECORDING",
  OPEN_SETTINGS: "OPEN_SETTINGS",
  BRING_TAB_TO_FRONT: "BRING_TAB_TO_FRONT",
  OPEN_NEW_TAB: "OPEN_NEW_TAB"
};
export {
  AgentToolName,
  EngineToWidgetAction,
  EngineToWidgetToolAction,
  WidgetToEngineAction
};
